"""OSGB Easting/Northing → SVG viewBox projection for the map panel.

The RJTTF (timetable) `.MSN` master station file carries every UK station
with its OSGB National Grid reference in a compact 5-digit form (spec
§5.1 of RSPS5046). Coordinates are in 100-metre units with a fixed
leading-digit offset:

    BNG easting  (metres) = (E_msn - 10000) * 100
    BNG northing (metres) = (N_msn - 60000) * 100

(Verified: London Euston MSN 15295/61827 → 529500/182700, the real
Euston grid reference.)

Stations MUST land in the same viewBox space as the GB coastline in
`frontend/live/assets/gb-outline.json` (generated by
tools/build_gb_outline.py). That asset embeds its own BNG→viewBox
projection (uniform scale, centred, y-flipped, 4px inset); we read those
parameters at import time and apply the identical transform, so a dot for
Liverpool sits on Liverpool, not in the Irish Sea. If the asset is
missing we fall back to constants captured from the committed asset.

Non-numeric or empty grid refs are dropped rather than fabricated —
consistent with CLAUDE.md's "resolver never silently guesses" rule
(a station with no coord is served with `x=null, y=null` and the map
just skips it).

Nothing here mutates state; everything is pure and file-only."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path


# SVG viewBox the delivered `index.html` map uses.
SVG_W = 420.0
SVG_H = 640.0

_OUTLINE_ASSET = (
    Path(__file__).resolve().parent.parent.parent
    / "frontend" / "live" / "assets" / "gb-outline.json"
)

# Fallbacks = the committed gb-outline.json's projection block, so the two
# stay aligned even if the asset can't be read at runtime.
_FALLBACK = {
    "scale": 0.0005340420626616078,
    "offset_x": 54.01039933191197,
    "offset_y": 4.0,
    "bng_min_e": 71421.10878092691,
    "bng_max_n": 1195232.0250207286,
}


def _load_projection() -> dict[str, float]:
    try:
        payload = json.loads(_OUTLINE_ASSET.read_text())
        proj = payload["projection"]
        bbox = payload["bbox_bng"]
        return {
            "scale": float(proj["scale"]),
            "offset_x": float(proj["offset_x"]),
            "offset_y": float(proj["offset_y"]),
            "bng_min_e": float(bbox[0]),
            "bng_max_n": float(bbox[3]),
        }
    except (OSError, KeyError, ValueError, IndexError):
        return dict(_FALLBACK)


_PROJ = _load_projection()


@dataclass(frozen=True)
class StationCoord:
    crs: str
    name: str
    easting: int
    northing: int
    x: float
    y: float


def project(easting: int, northing: int) -> tuple[float, float]:
    """MSN 100m-unit grid ref → viewBox point, via the outline's transform.

    Clamped to the viewBox so an off-grid station lands on the map's edge
    rather than escaping — the frontend can still render it while the
    analyst spots the anomaly."""
    bng_e = (easting - 10000) * 100.0
    bng_n = (northing - 60000) * 100.0
    x = _PROJ["offset_x"] + (bng_e - _PROJ["bng_min_e"]) * _PROJ["scale"]
    # Y-axis flipped: higher northing → smaller SVG y (top of viewport).
    y = _PROJ["offset_y"] + (_PROJ["bng_max_n"] - bng_n) * _PROJ["scale"]
    x = max(0.0, min(SVG_W, x))
    y = max(0.0, min(SVG_H, y))
    return round(x, 2), round(y, 2)


def _parse_msn_a_record(line: str) -> tuple[str, str, int, int] | None:
    """Parse one `A` (station) record from an `.MSN` master station file.

    Field offsets (RSPS5046 §5.1, cross-checked against known landmarks
    in RJTTF883.MSN):
      pos  5 .. 30    STATION_NAME  (26 chars, left-aligned, space-padded)
      pos 44 .. 46    CRS           (3 chars)
      pos 53 .. 57    EASTING       (5-digit, 100 m units)
      pos 59 .. 63    NORTHING      (5-digit, 100 m units)

    Returns `None` for the file-spec preamble line or any row whose
    grid reference isn't a clean integer — those are quarantined
    (we return None; caller drops), never invented."""
    if not line.startswith("A"):
        return None
    if len(line) < 63:
        return None
    name = line[5:30].strip()
    crs = line[43:46].strip()
    if not crs or not crs.isalnum():
        return None
    e_raw = line[52:57].strip()
    n_raw = line[58:63].strip()
    if not (e_raw.isdigit() and n_raw.isdigit()):
        return None
    easting = int(e_raw)
    northing = int(n_raw)
    # Guard against the "FILE-SPEC" preamble (which has huge numbers)
    # and any row with a zero grid ref (some closed / bus-only entries).
    if easting < 1000 or northing < 1000:
        return None
    return crs, name, easting, northing


def load_station_coords(msn_path: Path) -> dict[str, StationCoord]:
    """Read one MSN file and return {CRS: StationCoord} projected to SVG.

    First occurrence of a CRS wins — duplicate rows (regional variants,
    historic renames) are ignored so the map has exactly one dot per code."""
    out: dict[str, StationCoord] = {}
    with msn_path.open("r", encoding="latin-1") as f:
        for line in f:
            rec = _parse_msn_a_record(line.rstrip("\n"))
            if rec is None:
                continue
            crs, name, easting, northing = rec
            if crs in out:
                continue
            x, y = project(easting, northing)
            out[crs] = StationCoord(
                crs=crs, name=name,
                easting=easting, northing=northing,
                x=x, y=y,
            )
    return out


def default_msn_path(data_dir: Path) -> Path | None:
    """Pick the newest RJTTF*.MSN in `data_dir`, or None if absent."""
    candidates = sorted(Path(data_dir).glob("RJTTF*.MSN"))
    return candidates[-1] if candidates else None


__all__ = [
    "StationCoord",
    "project",
    "load_station_coords",
    "default_msn_path",
    "SVG_W", "SVG_H",
]
